//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_RPG_Prototyp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DZIALANIE
    {
        public int IDDZIALANIE { get; set; }
        public short IDFUNKCJA { get; set; }
        public int IDITEM { get; set; }
        public byte WARTOSC { get; set; }
    
        public virtual FUNKCJA FUNKCJA { get; set; }
        public virtual ITEM ITEM { get; set; }
    }
}
