//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_RPG_Prototyp
{
    using System;
    using System.Collections.Generic;
    
    public partial class KLASA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KLASA()
        {
            this.POSTAC = new HashSet<POSTAC>();
        }
    
        public int IDKLASA { get; set; }
        public string NAZWA { get; set; }
        public byte SILA { get; set; }
        public byte WYTRZYMALOSC { get; set; }
        public byte UDZWIG { get; set; }
        public byte MANA { get; set; }
        public byte HP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSTAC> POSTAC { get; set; }
    }
}
