//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_RPG_Prototyp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RpgSystemEntities : DbContext
    {
        public RpgSystemEntities()
            : base("name=RpgSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DZIALANIE> DZIALANIE { get; set; }
        public virtual DbSet<FUNKCJA> FUNKCJA { get; set; }
        public virtual DbSet<ITEM> ITEM { get; set; }
        public virtual DbSet<KATEGORIA> KATEGORIA { get; set; }
        public virtual DbSet<KLASA> KLASA { get; set; }
        public virtual DbSet<OCENA> OCENA { get; set; }
        public virtual DbSet<POSTAC> POSTAC { get; set; }
        public virtual DbSet<UZYTKOWNIK> UZYTKOWNIK { get; set; }
    }
}
