//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_RPG_Prototyp
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTAC
    {
        public int IDPOSTAC { get; set; }
        public int IDKLASA { get; set; }
        public int IDUZYTKOWNIK { get; set; }
        public string NAZWA { get; set; }
    
        public virtual KLASA KLASA { get; set; }
        public virtual UZYTKOWNIK UZYTKOWNIK { get; set; }
    }
}
